/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.magno;

public class Library {
    public boolean someLibraryMethod() {

        String test ="";
        System.out.println(test);
        return true;
    }
}
